In [14]:
import numpy as np

In [15]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
#inserting new col or row to this 2d array
#insert(array_name,index,values,axis=0 for row and 1 for col)
new_arr = np.insert(arr,0,[[13,14,15,16]],axis=0)
new_arr
#here we are shiftig all the rows one step down when inserting a new row

array([[13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
new_arr = np.insert(new_arr,3,[[17,18,19,20]],axis=1)
new_arr
#here we are shifting all the cols that are right to that index onse step right

array([[13, 14, 15, 17, 16],
       [ 1,  2,  3, 18,  4],
       [ 5,  6,  7, 19,  8],
       [ 9, 10, 11, 20, 12]])

In [19]:
#append
#it is similar to insert but we don't need to specify the index
new_arr = np.append(new_arr,[[21,22,23,24,25]],axis=0)
new_arr

array([[13, 14, 15, 17, 16],
       [ 1,  2,  3, 18,  4],
       [ 5,  6,  7, 19,  8],
       [ 9, 10, 11, 20, 12],
       [21, 22, 23, 24, 25]])

In [23]:
new_arr = np.append(new_arr,[[26,27,28,29,30]],axis=0)
print(new_arr)
print("length of rows = len(array)-->",len(new_arr))
print("length of cols = len(array[0])-->",len(new_arr[0]))

[[13 14 15 17 16]
 [ 1  2  3 18  4]
 [ 5  6  7 19  8]
 [ 9 10 11 20 12]
 [21 22 23 24 25]
 [26 27 28 29 30]]
length of rows = len(array)--> 6
length of cols = len(array[0])--> 5


In [29]:
#accessing 2d array elements
def access_2d_array(array,row_index,col_index):
    if row_index>len(array)-1 or col_index>len(array[0])-1:
        return "index does not match"
      
    return array[row_index][col_index]

print(access_2d_array(new_arr,3,5))
print(access_2d_array(new_arr,5,4))

index does not match
30


In [32]:
#traversing 2d array
print(new_arr)
for row_index in range(len(new_arr)):
    for col_index in range(len(new_arr[row_index])):
        print(new_arr[row_index][col_index])
    print("---")
        

[[13 14 15 17 16]
 [ 1  2  3 18  4]
 [ 5  6  7 19  8]
 [ 9 10 11 20 12]
 [21 22 23 24 25]
 [26 27 28 29 30]]
13
14
15
17
16
---
1
2
3
18
4
---
5
6
7
19
8
---
9
10
11
20
12
---
21
22
23
24
25
---
26
27
28
29
30
---


In [34]:
#removing row or col in 2d array
print(new_arr)
new_arr = np.delete(new_arr,0,axis=1)
print(new_arr)

[[13 14 15 17 16]
 [ 1  2  3 18  4]
 [ 5  6  7 19  8]
 [ 9 10 11 20 12]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[14 15 17 16]
 [ 2  3 18  4]
 [ 6  7 19  8]
 [10 11 20 12]
 [22 23 24 25]
 [27 28 29 30]]
